import path from "node:path";
import { fileURLToPath } from "node:url";
import { reactRouter } from "@react-router/dev/vite";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vitest/config";
import tsconfigPaths from "vite-tsconfig-paths";
import { VitePWA } from "vite-plugin-pwa";

/** App directory (e.g. getviews.vn-1); dependencies may be hoisted to the parent folder. */
const viteConfigDir = path.dirname(fileURLToPath(import.meta.url));

/**
 * Vendor chunking via Rolldown ``advancedChunks`` (migrated from
 * ``manualChunks`` 2026-06-10 — the migration the old comment block planned).
 *
 * Why: under Rolldown, ``manualChunks`` return values are advisory — its
 * chunk-merging pass redistributed small modules into whichever named chunk
 * it liked. Verified consequence (perf audit 2026-06-10): ``react/jsx-runtime``
 * was folded INTO the ``motion`` chunk and React core into ``icons``, so every
 * component chunk imported ``motion`` and the prerendered landing preloaded
 * 40 KB gz of animation code it never renders. ``advancedChunks`` groups are
 * enforced: React internals now live in ``react-vendor`` and ``motion`` is
 * pure animation code again, off the landing critical path.
 *
 * Priorities: higher wins when multiple tests match. ``react-vendor`` must
 * outrank everything so jsx-runtime/scheduler never migrate again; the
 * catch-all ``vendor`` sits at the bottom.
 */
const advancedChunks = {
  groups: [
    { name: "react-vendor", test: /node_modules\/(react|react-dom|scheduler)\//, priority: 100 },
    { name: "react-router", test: /node_modules\/(react-router|@remix-run)/, priority: 90 },
    { name: "radix-ui", test: /node_modules\/@radix-ui\//, priority: 80 },
    { name: "tanstack", test: /node_modules\/@tanstack\//, priority: 80 },
    { name: "supabase", test: /node_modules\/@supabase\//, priority: 80 },
    { name: "icons", test: /node_modules\/lucide-react\//, priority: 80 },
    // Match the actual motion package directories only — a broader
    // ``motion`` substring also matched unrelated transitive deps.
    { name: "motion", test: /node_modules\/(motion|framer-motion)\//, priority: 80 },
    { name: "vendor", test: /node_modules\//, priority: 10 },
  ],
};

export default defineConfig({
  server: {
    fs: {
      // Hoisted installs: @react-router/dev resolves from ../node_modules, which Vite
      // serves as /@fs/<parent>/... — outside the app root by default → 403 and a blank page.
      allow: [path.resolve(viteConfigDir, "..")],
    },
  },
  build: {
    rollupOptions: {
      output: {
        advancedChunks,
      },
    },
  },
  plugins: [
    tailwindcss(),
    reactRouter(),
    tsconfigPaths({ projects: ["./tsconfig.app.json"] }),

    VitePWA({
      // ``prompt`` (not autoUpdate) — autoUpdate forced every cold
      // load including the unauthenticated landing to perform a
      // ``navigator.serviceWorker.register`` round-trip *before*
      // the app could skip the SW update loop, costing ~500 ms TTI
      // on slow networks. With ``prompt`` we surface a Vietnamese
      // "có bản cập nhật mới" banner via ``<PwaUpdatePrompt>`` in
      // root.tsx and let the user opt in.
      registerType: "prompt",
      manifest: false, // Use static public/manifest.json
      workbox: {
        // React Router v7 client build writes here (not Vite default ``dist/``).
        globDirectory: "build/client",
        globPatterns: ["**/*.{js,mjs,css,html,ico,png,svg,webp,woff2,json}"],
        // ``index.html`` is the SPA shell for all client-side routes.
        // React Router v7 SPA mode (ssr: false) uses createRoot — not hydrateRoot — for
        // non-prerendered routes, so serving index.html for /app/* is safe: React 18
        // detects the prerendered landing content, recovers gracefully, and renders the
        // correct client tree. ``/__spa-fallback.html`` was never generated by the
        // RR v7 build, so Workbox threw ``non-precached-url`` at SW install time.
        navigateFallback: "/index.html",
        navigateFallbackDenylist: [/^\/api\//],
        cleanupOutdatedCaches: true,
        // Ensures Workbox always has a runtime strategy even if globs miss (Rolldown edge cases).
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
            handler: "CacheFirst",
            options: {
              cacheName: "google-fonts",
              expiration: { maxEntries: 16, maxAgeSeconds: 60 * 60 * 24 * 365 },
            },
          },
        ],
      },
    }),
  ],
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    globals: true,
    env: {
      VITE_SUPABASE_URL: "https://test-project.supabase.co",
      VITE_SUPABASE_PUBLISHABLE_KEY: "vitest-publishable-key-placeholder",
    },
  },
});
