import path from "node:path";
import { fileURLToPath } from "node:url";
import { reactRouter } from "@react-router/dev/vite";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vitest/config";
import tsconfigPaths from "vite-tsconfig-paths";
import { VitePWA } from "vite-plugin-pwa";

/** App directory (e.g. getviews.vn-1); dependencies may be hoisted to the parent folder. */
const viteConfigDir = path.dirname(fileURLToPath(import.meta.url));

/** Split heavy vendors so chunks cache independently and initial parse stays smaller on mobile. */
function manualChunks(id: string) {
  if (!id.includes("node_modules")) return;
  const n = id.replace(/\\/g, "/");
  if (n.includes("@radix-ui")) return "radix-ui";
  if (n.includes("@tanstack")) return "tanstack";
  if (n.includes("@supabase")) return "supabase";
  if (n.includes("lucide-react")) return "icons";
  // Match the actual motion package directories. The broader
  // ``includes("motion")`` predicate also matched any node_modules
  // path with "motion" anywhere (e.g. nested transitive deps with
  // ``motion`` in their filename) and risked accidentally hoisting
  // unrelated modules into the motion chunk.
  if (n.includes("/motion/") || n.includes("/framer-motion/")) return "motion";
  if (n.includes("react-router") || n.includes("@remix-run")) return "react-router";
  // KNOWN: ``react-vendor`` does not currently emit as a separate chunk
  // under Rolldown — the matcher fires (verified via debug logging) and
  // returns "react-vendor", but Rolldown's chunk-merging pass folds it
  // into the generic ``vendor`` bundle anyway. Bundle audit 2026-04-25
  // confirmed the React/react-dom/scheduler bytes (~117 KB raw) ride
  // ``vendor-*.js``. Long-tail caching wins from a separate React chunk
  // are deferred until we either bisect a Rolldown option that respects
  // the return value here or migrate the chunking strategy to
  // ``output.advancedChunks``.
  if (
    n.includes("/react-dom/") ||
    n.includes("/scheduler/") ||
    /\/react\/[^/]/.test(n)
  )
    return "react-vendor";
  return "vendor";
}

export default defineConfig({
  server: {
    fs: {
      // Hoisted installs: @react-router/dev resolves from ../node_modules, which Vite
      // serves as /@fs/<parent>/... — outside the app root by default → 403 and a blank page.
      allow: [path.resolve(viteConfigDir, "..")],
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks,
      },
    },
  },
  plugins: [
    tailwindcss(),
    reactRouter(),
    tsconfigPaths({ projects: ["./tsconfig.app.json"] }),

    VitePWA({
      // ``prompt`` (not autoUpdate) — autoUpdate forced every cold
      // load including the unauthenticated landing to perform a
      // ``navigator.serviceWorker.register`` round-trip *before*
      // the app could skip the SW update loop, costing ~500 ms TTI
      // on slow networks. With ``prompt`` we surface a Vietnamese
      // "có bản cập nhật mới" banner via ``<PwaUpdatePrompt>`` in
      // root.tsx and let the user opt in.
      registerType: "prompt",
      manifest: false, // Use static public/manifest.json
      workbox: {
        // React Router v7 client build writes here (not Vite default ``dist/``).
        globDirectory: "build/client",
        globPatterns: ["**/*.{js,mjs,css,html,ico,png,svg,webp,woff2,json}"],
        // ``index.html`` is the SPA shell for all client-side routes.
        // React Router v7 SPA mode (ssr: false) uses createRoot — not hydrateRoot — for
        // non-prerendered routes, so serving index.html for /app/* is safe: React 18
        // detects the prerendered landing content, recovers gracefully, and renders the
        // correct client tree. ``/__spa-fallback.html`` was never generated by the
        // RR v7 build, so Workbox threw ``non-precached-url`` at SW install time.
        navigateFallback: "/index.html",
        navigateFallbackDenylist: [/^\/api\//],
        cleanupOutdatedCaches: true,
        // Ensures Workbox always has a runtime strategy even if globs miss (Rolldown edge cases).
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
            handler: "CacheFirst",
            options: {
              cacheName: "google-fonts",
              expiration: { maxEntries: 16, maxAgeSeconds: 60 * 60 * 24 * 365 },
            },
          },
        ],
      },
    }),
  ],
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    globals: true,
    env: {
      VITE_SUPABASE_URL: "https://test-project.supabase.co",
      VITE_SUPABASE_PUBLISHABLE_KEY: "vitest-publishable-key-placeholder",
    },
  },
});
