-- Backfill cross-niche ingest rows (2026-05-27 03:00-07:30 ICT) to in-niche HI-11 class.
-- Generated by cloud-run/scripts/backfill_cross_niche_in_niche.py logic.

BEGIN;

CREATE TEMP TABLE _backfill_cross_niche (
  video_id text PRIMARY KEY,
  new_content_class_id int NOT NULL,
  new_inferred_creator_niche_id int,
  backfill_reason text NOT NULL
) ON COMMIT DROP;

INSERT INTO _backfill_cross_niche (video_id, new_content_class_id, new_inferred_creator_niche_id, backfill_reason)
VALUES
  ('7639379245097176328'::text, 51, NULL, 'in_niche_route'),
  ('7640497388158831893'::text, 59, 14, 'in_niche_route'),
  ('7641226540411276564'::text, 59, 14, 'in_niche_route'),
  ('7641585286316674324'::text, 49, NULL, 'fallback_junction_miss'),
  ('7641889772092443907'::text, 63, 11, 'fallback_junction_miss'),
  ('7641959422780001554'::text, 63, 11, 'in_niche_route'),
  ('7642029028609756424'::text, 56, 14, 'fallback_junction_miss'),
  ('7642132459613654280'::text, 41, 8, 'in_niche_route'),
  ('7642168434045865224'::text, 60, 11, 'in_niche_route'),
  ('7642180181771259154'::text, 35, 7, 'fallback_junction_miss'),
  ('7642216585419050247'::text, 56, 14, 'fallback_junction_miss'),
  ('7642234903337241874'::text, 51, NULL, 'fallback_junction_miss'),
  ('7642511320213966087'::text, 41, 8, 'in_niche_route'),
  ('7642652826384043285'::text, 63, 11, 'in_niche_route'),
  ('7642660735121739029'::text, 51, NULL, 'fallback_junction_miss'),
  ('7642698183495257362'::text, 45, NULL, 'in_niche_route'),
  ('7642914113781337352'::text, 51, NULL, 'fallback_junction_miss'),
  ('7642939167953014024'::text, 6, 2, 'in_niche_route'),
  ('7643067608354295061'::text, 43, 8, 'in_niche_route'),
  ('7643071224540564754'::text, 6, 2, 'in_niche_route'),
  ('7643091081311325461'::text, 60, 11, 'in_niche_route'),
  ('7643390783621483797'::text, 33, 6, 'fallback_junction_miss'),
  ('7643408341405895954'::text, 73, 4, 'fallback_low_conf'),
  ('7643650632951418120'::text, 64, 11, 'fallback_junction_miss'),
  ('7643662781165686037'::text, 51, NULL, 'fallback_junction_miss'),
  ('7643674135272361236'::text, 65, 12, 'fallback_junction_miss'),
  ('7643707630610828564'::text, 16, 4, 'in_niche_route'),
  ('7643710554384682261'::text, 16, 4, 'in_niche_route'),
  ('7643736522444918037'::text, 59, 14, 'in_niche_route'),
  ('7643757423546748180'::text, 12, 3, 'in_niche_route'),
  ('7643769481033944341'::text, 41, 8, 'in_niche_route'),
  ('7643779664535653652'::text, 19, 4, 'fallback_low_conf'),
  ('7643785224077298952'::text, 19, 4, 'fallback_low_conf'),
  ('7643810642561862932'::text, 9, 2, 'in_niche_route'),
  ('7643811031612951829'::text, 51, NULL, 'fallback_junction_miss'),
  ('7643813853414952210'::text, 49, NULL, 'in_niche_route'),
  ('7643826828498537744'::text, 73, 4, 'fallback_low_conf'),
  ('7643851859454627093'::text, 66, 12, 'in_niche_route'),
  ('7643982250861759764'::text, 63, 11, 'in_niche_route'),
  ('7643988839836519687'::text, 33, 6, 'fallback_junction_miss'),
  ('7643996962055834900'::text, 65, 12, 'fallback_junction_miss'),
  ('7644027072418974994'::text, 51, NULL, 'fallback_junction_miss'),
  ('7644032129881378069'::text, 41, 8, 'in_niche_route'),
  ('7644033387790929172'::text, 63, 11, 'fallback_junction_miss'),
  ('7644048046325599508'::text, 30, 6, 'in_niche_route'),
  ('7644053137707355413'::text, 7, 2, 'fallback_low_conf'),
  ('7644096607473929493'::text, 47, NULL, 'in_niche_route'),
  ('7644108122935708948'::text, 33, 6, 'fallback_junction_miss');

UPDATE video_corpus v
SET
  content_class_id = b.new_content_class_id,
  inferred_creator_niche_id = COALESCE(b.new_inferred_creator_niche_id, v.inferred_creator_niche_id)
FROM _backfill_cross_niche b
WHERE v.video_id = b.video_id;

COMMIT;
