import { createClient, SupabaseClient } from "@supabase/supabase-js";
// NOTE: Database type is generated by `supabase gen types typescript` during /init.
// This file will show a TS error until database.types.ts exists in shared/types/.
import type { Database } from "../types/database.types";

/**
 * Platform-agnostic Supabase client factory.
 * Each platform passes its own storage adapter:
 * - Web: localStorage
 * - Mobile: ExpoSecureStoreAdapter
 */
export function createSupabaseClient(
  url: string,
  key: string,
  storage: any
): SupabaseClient<Database> {
  return createClient<Database>(url, key, {
    auth: {
      storage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: typeof window !== "undefined" && !!window.location,
    },
  });
}
