import { createContext, useContext } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
// NOTE: Database type is generated by `supabase gen types typescript` during /init.
// This file will show a TS error until database.types.ts exists in shared/types/.
import type { Database } from "../types/database.types";

const SupabaseContext = createContext<SupabaseClient<Database> | null>(null);

/**
 * Wrap your root layout with this provider.
 * Web: <SupabaseProvider value={webClient}>
 * Mobile: <SupabaseProvider value={mobileClient}>
 */
export const SupabaseProvider = SupabaseContext.Provider;

/**
 * Access the platform-specific Supabase client from shared hooks.
 * Throws if used outside SupabaseProvider — catches missing setup early.
 */
export function useSupabase(): SupabaseClient<Database> {
  const client = useContext(SupabaseContext);
  if (!client) {
    throw new Error(
      "useSupabase must be used within <SupabaseProvider>. " +
        "Wrap your root layout with <SupabaseProvider value={client}>."
    );
  }
  return client;
}
